[VOY-610] [DEV-ONLY] Test against Python 3.9, add linter, conform to standards
styleseat/ss-instrumentation pull request #18
Opened 2021-09-14 18:20 UTC by elijahr

Story: https://styleseat.atlassian.net/browse/VOY-610

2021-09-15 17:29 UTC, CaleHarter approved these changes

2021-09-17 17:21 UTC, amethystmarie requested changes
We'll also need a corresponding PR in the styleseat repo to update our usage of ss-instrumentation to point to the new version.

2021-09-17 17:21 UTC, amethystmarie commented on .github/pull_request_template.md
> +- [ ] README and/or Confluence documentation has been updated, if needed.
I think there should be a checklist item for bumping major or minor version as necessary and updating the referenced version in dependent repos.

2021-09-17 17:21 UTC, amethystmarie commented on setup.py
> +    author="Some Dude at StyleSeat",
Can we change the author to be something real instead of a joke?

2021-09-17 17:24 UTC, amethystmarie commented
Can we automate the tagging when the version number changes?

2021-09-17 17:38 UTC, elijahr commented
> Can we automate the tagging when the version number changes?

@amethystmarie interesting point. Cursory research leads me to https://github.com/laputansoft/github-tag-action. Looks like that will do what we want, if we provide the `tag` parameter, so that it doesn't automatically bump the version for us.

2021-09-17 19:02 UTC, elijahr commented on package.json
> +  "version": "2.0.0",
Note for self: why does this package have both a setup.py and a package.json?

2021-09-21 20:23 UTC, elijahr commented on package.json
> +  "version": "2.0.0",
(becase npm is used for deploying this, via serverless)

2021-09-21 21:58 UTC, CaleHarter approved these changes

2021-09-22 02:13 UTC, amethystmarie commented on .circleci/config.yml
> +                - dev
What do you think about not having a hold on tagging the release? Who would be pushing this button if we keep it?

2021-09-22 21:43 UTC, amethystmarie reviewed
the deploy_stage and deploy_prod don't really do anything, right?

2021-09-22 21:46 UTC, elijahr commented
@amethystmarie 

> the deploy_stage and deploy_prod don't really do anything, right?

from what i can tell, they use serverless to deploy `flusher.py`, which runs every minute. presumably this service is still running.

2021-09-24 22:14 UTC, amethystmarie approved these changes

2021-09-27 18:13 UTC, merged